-- CreateTable
CREATE TABLE "Tier" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "description" STRING NOT NULL,

    CONSTRAINT "Tier_pkey" PRIMARY KEY ("id")
);
